# Generated by Django 3.2.13 on 2022-06-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
